apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gyig
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0028-tenant/tkrw-pr712-0075-0028-app/devfile-sample-gyig@sha256:65d4854743a7cae9efb36d0f906d1dc4b3bd45aba04101895a47f75e2a4386cf
        name: my-nodejs
        resources: {}
status: {}
